import org.apache.log4j.Logger;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;

class html2bb
{
	public static final Logger LOG=Logger.getLogger(html2bb.class);
	/**
	 * @param html
	 * @return
	 */
	public static String parse(String html)
	{
		//LOG.info("//Parsing START");
		try 
		{
			Document doc = Jsoup.parse(html);
			doc.select("label").remove();
			doc.select("input").remove();
			doc.select("script").remove();
			doc.select("textarea").remove();

			doc.select("*").removeAttr("alt");
			doc.select("*").removeAttr("title");
			doc.select("*").removeAttr("style");
			doc.select("*").removeAttr("id");
			doc.select("*").removeAttr("class");
			doc.select("*").removeAttr("width");
			doc.select("*").removeAttr("height");
			doc.select("*").removeAttr("target");
		
			html = doc.body().html();
			
		}catch(Exception e){LOG.error("ERROR Jsoup"+e);}
		//for(Element elm :doc.getAllElements()){if(elm.tagName()=="embed"){String src = elm.attr("src");}}
		html = html.replaceAll("&nbsp;|&#160;"," ");
		html = html.replaceAll("&iexcl;|&#161;","¡");
		html = html.replaceAll("&cent;|&#162;","¢");
		html = html.replaceAll("&pound;|&#163;","£");
		html = html.replaceAll("&curren;|&#164;","¤");
		html = html.replaceAll("&yen;|&#165;","¥");
		html = html.replaceAll("&brvbar;|&#166;","¦");
		html = html.replaceAll("&sect;|&#167;","§");
		html = html.replaceAll("&uml;|&#168;","¨");
		html = html.replaceAll("&copy;|&#169;","©");
		html = html.replaceAll("&ordf;|&#170;","ª");
		html = html.replaceAll("&laquo;|&#171;","«");
		html = html.replaceAll("&raquo;|&#187;","»");
		html = html.replaceAll("&not;|&#172;","¬");
		html = html.replaceAll("&reg;|&#174;","®");
		html = html.replaceAll("&macr;|&#175;","¯");
		html = html.replaceAll("&deg;|&#176;","°");
		html = html.replaceAll("&plusmn;|&#177;","±");
		html = html.replaceAll("&sup2;|&#178;","²");
		html = html.replaceAll("&sup3;|&#179;","³");
		html = html.replaceAll("&acute;|&#180;","´");
		html = html.replaceAll("&micro;|&#181;","µ");
		html = html.replaceAll("&para;|&#182;","¶");
		html = html.replaceAll("&middot;|&#183;","·");
		html = html.replaceAll("&cedil;|&#184;","¸");
		html = html.replaceAll("&sup1;|&#185;","¹	");
		html = html.replaceAll("&ordm;|&#186;","º");
		html = html.replaceAll("&frac14;|&#188;","¼");
		html = html.replaceAll("&frac12;|&#189;","½");
		html = html.replaceAll("&#8531;","⅓");
		html = html.replaceAll("&frac34;|&#190;","¾");
		html = html.replaceAll("&iquest;|&#191;","¿");
		html = html.replaceAll("&Agrave;|&#192;","À");
		html = html.replaceAll("&Aacute;|&#193;","Á");
		html = html.replaceAll("&Acirc;|&#194;","Â");
		html = html.replaceAll("&Atilde;|&#195;","Ã");
		html = html.replaceAll("&Auml;|&#196;","Ä");
		html = html.replaceAll("&Aring;|&#197;","Å");
		html = html.replaceAll("&AElig;|&#198;","Æ");
		html = html.replaceAll("&Ccedil;|&#199;","Ç");
		html = html.replaceAll("&Egrave;|&#200;","È");
		html = html.replaceAll("&Eacute;|&#201;","É");
		html = html.replaceAll("&Ecirc;|&#202;","Ê");
		html = html.replaceAll("&Euml;|&#203;","Ë");
		html = html.replaceAll("&Igrave;|&#204;","Ì");
		html = html.replaceAll("&Iacute;|&#205;","Í");
		html = html.replaceAll("&Icirc;|&#206;","Î");
		html = html.replaceAll("&Iuml;|&#207;","Ï");
		html = html.replaceAll("&ETH;|&#208;","Ð");
		html = html.replaceAll("&Ntilde;|&#209;","Ñ");
		html = html.replaceAll("&Ograve;|&#210;","Ò");
		html = html.replaceAll("&Oacute;|&#211;","Ó");
		html = html.replaceAll("&Ocirc;|&#212;","Ô");
		html = html.replaceAll("&Otilde;|&#213;","Õ");
		html = html.replaceAll("&Ouml;|&#214;","Ö");
		html = html.replaceAll("&times;|&#215;","×");
		html = html.replaceAll("&Oslash;|&#216;","Ø");
		html = html.replaceAll("&Ugrave;|&#217;","Ù");
		html = html.replaceAll("&Uacute;|&#218;","Ú");
		html = html.replaceAll("&Ucirc;|&#219;","Û");
		html = html.replaceAll("&Uuml;|&#220;","Ü");
		html = html.replaceAll("&Yacute;|&#221;","Ý");
		html = html.replaceAll("&THORN;|&#222;","Þ");
		html = html.replaceAll("&szlig;|&#223;","ß");
		html = html.replaceAll("&agrave;|&#224;","à");
		html = html.replaceAll("&aacute;|&#225;","á");
		html = html.replaceAll("&acirc;|&#226;","â");
		html = html.replaceAll("&atilde;|&#227;","ã");
		html = html.replaceAll("&auml;|&#228;","ä");
		html = html.replaceAll("&aring;|&#229;","å");
		html = html.replaceAll("&aelig;|&#230;","æ");
		html = html.replaceAll("&ccedil;|&#231;","ç");
		html = html.replaceAll("&egrave;|&#232;","è");
		html = html.replaceAll("&eacute;|&#233;","é");
		html = html.replaceAll("&ecirc;|&#234;","ê");
		html = html.replaceAll("&euml;|&#235;","ë");
		html = html.replaceAll("&igrave;|&#236;","ì");
		html = html.replaceAll("&iacute;|&#237;","í");
		html = html.replaceAll("&icirc;|&#238;","î");
		html = html.replaceAll("&iuml;|&#239;","ï");
		html = html.replaceAll("&eth;|&#240;","ð");
		html = html.replaceAll("&ntilde;|&#241;","ñ");
		html = html.replaceAll("&ograve;|&#242;","ò");
		html = html.replaceAll("&oacute;|&#243;","ó");
		html = html.replaceAll("&ocirc;|&#244;","ô");
		html = html.replaceAll("&otilde;|&#245;","õ");
		html = html.replaceAll("&ouml;|&#246;","ö");
		html = html.replaceAll("&divide;|&#247;","÷");
		html = html.replaceAll("&oslash;|&#248;","ø");
		html = html.replaceAll("&ugrave;|&#249;","ù");
		html = html.replaceAll("&uacute;|&#250;","ú");
		html = html.replaceAll("&ucirc;|&#251;","û");
		html = html.replaceAll("&uuml;|&#252;","ü");
		html = html.replaceAll("&yacute;|&#253;","ý");
		html = html.replaceAll("&thorn;|&#254;","þ");
		html = html.replaceAll("&yuml;|&#255;","ÿ");
		html = html.replaceAll("&fnof;|&#402;","ƒ");
		html = html.replaceAll("&Alpha;|&#913;","Α");
		html = html.replaceAll("&Beta;|&#914;","Β");
		html = html.replaceAll("&Gamma;|&#915;","Γ");
		html = html.replaceAll("&Delta;|&#916;","Δ");
		html = html.replaceAll("&Epsilon;|&#917;","Ε");
		html = html.replaceAll("&Zeta;|&#918;","Ζ");
		html = html.replaceAll("&Eta;|&#919;","Η");
		html = html.replaceAll("&Theta;|&#920;","Θ");
		html = html.replaceAll("&Iota;|&#921;","Ι");
		html = html.replaceAll("&Kappa;|&#922;","Κ");
		html = html.replaceAll("&Lambda;|&#923;","Λ");
		html = html.replaceAll("&Mu;|&#924;","Μ");
		html = html.replaceAll("&Nu;|&#925;","Ν");
		html = html.replaceAll("&Xi;|&#926;","Ξ");
		html = html.replaceAll("&Omicron;|&#927;","Ο");
		html = html.replaceAll("&Pi;|&#928;","Π");
		html = html.replaceAll("&Rho;|&#929;","Ρ");
		html = html.replaceAll("&Sigma;|&#931;","Σ");
		html = html.replaceAll("&Tau;|&#932;","Τ");
		html = html.replaceAll("&Upsilon;|&#933;","Υ");
		html = html.replaceAll("&Phi;|&#934;","Φ");
		html = html.replaceAll("&Chi;|&#935;","Χ");
		html = html.replaceAll("&Psi;|&#936;","Ψ");
		html = html.replaceAll("&Omega;|&#937;","Ω");
		html = html.replaceAll("&alpha;|&#945;","α");
		html = html.replaceAll("&beta;|&#946;","β");
		html = html.replaceAll("&gamma;|&#947;","γ");
		html = html.replaceAll("&delta;|&#948;","δ");
		html = html.replaceAll("&epsilon;|&#949;","ε");
		html = html.replaceAll("&zeta;|&#950;","ζ");
		html = html.replaceAll("&eta;|&#951;","η");
		html = html.replaceAll("&theta;|&#952;","θ");
		html = html.replaceAll("&iota;|&#953;","ι");
		html = html.replaceAll("&kappa;|&#954;","κ");
		html = html.replaceAll("&lambda;|&#955;","λ");
		html = html.replaceAll("&mu;|&#956;","μ");
		html = html.replaceAll("&nu;|&#957;","ν");
		html = html.replaceAll("&xi;|&#958;","ξ");
		html = html.replaceAll("&omicron;|&#959;","ο");
		html = html.replaceAll("&pi;|&#960;","π");
		html = html.replaceAll("&rho;|&#961;","ρ");
		html = html.replaceAll("&sigmaf;|&#962;","ς");
		html = html.replaceAll("&sigma;|&#963;","σ");
		html = html.replaceAll("&tau;|&#964;","τ");
		html = html.replaceAll("&upsilon;|&#965;","υ");
		html = html.replaceAll("&phi;|&#966;","φ");
		html = html.replaceAll("&chi;|&#967;","χ");
		html = html.replaceAll("&psi;|&#968;","ψ");
		html = html.replaceAll("&omega;|&#969;","ω");
		html = html.replaceAll("&thetasy;|&#977;","ϑ");
		html = html.replaceAll("&upsih;|&#978;","ϒ");
		html = html.replaceAll("&piv;|&#982;","ϖ");
		html = html.replaceAll("&bull;|&#8226;","•");
		html = html.replaceAll("&hellip;|&#8230;","…");
		html = html.replaceAll("&prime;|&#8242;","′");
		html = html.replaceAll("&Prime;|&#8243;","″");
		html = html.replaceAll("&oline;|&#8254;","‾");
		html = html.replaceAll("&frasl;|&#8260;","⁄");
		html = html.replaceAll("&weierp;|&#8472;","℘");
		html = html.replaceAll("&image;|&#8465;","ℑ");
		html = html.replaceAll("&real;|&#8476;","ℜ");
		html = html.replaceAll("&trade;|&#8482;","™");
		html = html.replaceAll("&alefsym;|&#8501;","ℵ");
		html = html.replaceAll("&larr;|&#8592;","←");
		html = html.replaceAll("&uarr;|&#8593;","↑");
		html = html.replaceAll("&rarr;|&#8594;","→");
		html = html.replaceAll("&darr;|&#8595;","↓");
		html = html.replaceAll("&#9668;","◄");
		html = html.replaceAll("&#9650;","▲");
		html = html.replaceAll("&#9658;","►");
		html = html.replaceAll("&#9660;","▼");
		html = html.replaceAll("&harr;|&#8596;","↔");
		html = html.replaceAll("&crarr;|&#8629;","↵");
		html = html.replaceAll("&lArr;|&#8656;","⇐");
		html = html.replaceAll("&uArr;|&#8657;","⇑");
		html = html.replaceAll("&rArr;|&#8658;","⇒");
		html = html.replaceAll("&dArr;|&#8659;","⇓");
		html = html.replaceAll("&hArr;|&#8660;","⇔");
		html = html.replaceAll("&forall;|&#8704;","∀");
		html = html.replaceAll("&part;|&#8706;","∂");
		html = html.replaceAll("&exist;|&#8707;","∃");
		html = html.replaceAll("&empty;|&#8709;","∅");
		html = html.replaceAll("&nabla;|&#8711;","∇");
		html = html.replaceAll("&isin;|&#8712;","∈");
		html = html.replaceAll("&notin;|&#8713;","∉");
		html = html.replaceAll("&ni;|&#8715;","∋");
		html = html.replaceAll("&prod;|&#8719;","∏");
		html = html.replaceAll("&sum;|&#8721;","∑");
		html = html.replaceAll("&minus;|&#8722;","−");
		html = html.replaceAll("&lowast;|&#8727;","∗");
		html = html.replaceAll("&radic;|&#8730;","√");
		html = html.replaceAll("&prop;|&#8733;","∝");
		html = html.replaceAll("&infin;|&#8734;","∞");
		html = html.replaceAll("&ang;|&#8736;","∠");
		html = html.replaceAll("&and;|&#8743;","∧");
		html = html.replaceAll("&or;|&#8744;","∨");
		html = html.replaceAll("&cap;|&#8745;","∩");
		html = html.replaceAll("&cup;|&#8746;","∪");
		html = html.replaceAll("&int;|&#8747;","∫");
		html = html.replaceAll("&there4;|&#8756;","∴");
		html = html.replaceAll("&sim;|&#8764;","∼");
		html = html.replaceAll("&cong;|&#8773;","≅");
		html = html.replaceAll("&asymp;|&#8776;","≈");
		html = html.replaceAll("&ne;|&#8800;","≠");
		html = html.replaceAll("&equiv;|&#8801;","≡");
		html = html.replaceAll("&le;|&#8804;","≤");
		html = html.replaceAll("&ge;|&#8805;","≥");
		html = html.replaceAll("&sub;|&#8834;","⊂");
		html = html.replaceAll("&sup;|&#8835;","⊃");
		html = html.replaceAll("&nsub;|&#8836;","⊄");
		html = html.replaceAll("&sube;|&#8838;","⊆");
		html = html.replaceAll("&supe;|&#8839;","⊇");
		html = html.replaceAll("&oplus;|&#8853;","⊕");
		html = html.replaceAll("&otimes;|&#8855;","⊗");
		html = html.replaceAll("&perp;|&#8869;","⊥");
		html = html.replaceAll("&sdot;|&#8901;","⋅");
		html = html.replaceAll("&loz;|&#9674;","◊");
		html = html.replaceAll("&spades;|&#9824;","♠");
		html = html.replaceAll("&clubs;|&#9827;","♣");
		html = html.replaceAll("&hearts;|&#9829;","♥");
		html = html.replaceAll("&diams;|&#9830;","♦");
		html = html.replaceAll("&apos;|&#39;","'");
		html = html.replaceAll("&quot;|&#34;","\"");
		html = html.replaceAll("&amp;|&#38;","&");
		html = html.replaceAll("&lt;|&#60;","<");
		html = html.replaceAll("&gt;|&#62;",">");
		html = html.replaceAll("&OElig;|&#338;","Œ");
		html = html.replaceAll("&oelig;|&#339;","œ");
		html = html.replaceAll("&Scaron;|&#352;","Š");
		html = html.replaceAll("&scaron;|&#353;","š");
		html = html.replaceAll("&Yuml;|&#376;","Ÿ");
		html = html.replaceAll("&circ;|&#710;","ˆ");
		html = html.replaceAll("&tilde;|&#732;","˜");
		html = html.replaceAll("&#8209;","‑");
		html = html.replaceAll("&ndash;|&#8211;","–");
		html = html.replaceAll("&mdash;|&#8212;","—");
		html = html.replaceAll("&lsquo;|&#8216;","‘");
		html = html.replaceAll("&rsquo;|&#8217;","’");
		html = html.replaceAll("&sbquo;|&#8218;","‚");
		html = html.replaceAll("&ldquo;|&#8220;","“");
		html = html.replaceAll("&rdquo;|&#8221;","”");
		html = html.replaceAll("&bdquo;|&#8222;","„");
		html = html.replaceAll("&dagger;|&#8224;","†");
		html = html.replaceAll("&Dagger;|&#8225;","‡");
		html = html.replaceAll("&permil;|&#8240;","‰");
		html = html.replaceAll("&lsaquo;|&#8249;","‹");
		html = html.replaceAll("&rsaquo;|&#8250;","›");
		html = html.replaceAll("&euro;|&#8364;","€");
		html = html.replaceAll("&#8470;","№");
		html = html.replaceAll("&#769;","́");

		html = html.replaceAll("&(.*?);","");//Удаляем все остальные мнемоники
		//****************************************************************
		html = html.replaceAll("< *hr( .*?)?>","[hr]");
		html = html.replaceAll("< *table( .*?)?>","[table]");
		html = html.replaceAll("< */ *table *>","[/table]");
		html = html.replaceAll("< *tr( .*?)?>","[tr]");
		html = html.replaceAll("< */ *tr *>","[/tr]");
		html = html.replaceAll("< *td( .*?)?>","[td]");
		html = html.replaceAll("< */ *td *>","[/td]");
		html = html.replaceAll("< *sub( .*?)?>","[sub]");
		html = html.replaceAll("< */ *sub *>","[/sub]");
		html = html.replaceAll("< *sup( .*?)?>","[sup]");
		html = html.replaceAll("< */ *sup *>","[/sup]");
		//****************************************************************		
		html = html.replaceAll("< *(b|strong)( .*?)?>","[b]");
		html = html.replaceAll("< */ *(b|strong) *>","[/b]");
		//****************************************************************		
		html = html.replaceAll("< *u( .*?)?>","[u]");
		html = html.replaceAll("< */ *u *>","[/u]");
		//****************************************************************
		html = html.replaceAll("< *(i|em)( .*?)?>","[i]");
		html = html.replaceAll("< */ *(i|em) *>","[/i]");
		//****************************************************************
		html = html.replaceAll("< *s( .*?)?>","[s]");
		html = html.replaceAll("< */ *s *>","[/s]");
		html = html.replaceAll("< *del( .*?)?>","[s]");
		html = html.replaceAll("< */ *del *>","[/s]");
		//****************************************************************
		html = html.replaceAll("< *blockquote( .*?)?>","[quote]");
		html = html.replaceAll("< */ *blockquote *>","[/quote]");
		//****************************************************************
		html = html.replaceAll("< *ul( .*?)?>","[list]");
		html = html.replaceAll("< */ *ul *>","[/list]");
		html = html.replaceAll("< *ol( .*?)?>","[list]");
		html = html.replaceAll("< */ *ol *>","[/list]");
		html = html.replaceAll("< *li( .*?)?>","[*]");
		html = html.replaceAll("< */ *li *>","");
		html = html.replaceAll("< *img( .*?)?src *= *('|\")(.*?)('|\")(.*?)? */? *>","[img]$3[/img]");
		//****************************************************************
		html = html.replaceAll("< *a( .*?)?href *= *('|\")(.*?)('|\")(.*?)? */? *>","[url=$3]");
		html = html.replaceAll("< */ *a *>","[/url]");
		//****************************************************************
		html = html.replaceAll("< *h1( .*?)?>","[size=\"20\"]");
		html = html.replaceAll("< *h2( .*?)?>","[size=\"18\"]");
		html = html.replaceAll("< *h3( .*?)?>","[size=\"16\"]");
		html = html.replaceAll("< *h4( .*?)?>","[size=\"14\"]");
		html = html.replaceAll("< *h5( .*?)?>","[size=\"12\"]");
		html = html.replaceAll("< *h6( .*?)?>","[size=\"10\"]");
		html = html.replaceAll("< */ *h[1-6] *>","[/size]");
		//****************************************************************
		html = html.replaceAll("< *iframe( .*?)?src *= *('|\")(.*?)('|\")(.*?)? */? *>","$3");
		html = html.replaceAll("< */ *iframe *>","");
		html = html.replaceAll("< *embed( .*?)?src *= *('|\")(.*?)('|\")(.*?)? */? *>","$3");
		html = html.replaceAll("< *object( .*?)?>","");
		html = html.replaceAll("< */ *object *>","");
		html = html.replaceAll("< *param( .*?)?>","");
		html = html.replaceAll("< */ *param *>","");
		//****************************************************************
		html = html.replaceAll("< *font( .*?)?>","[font]");
		html = html.replaceAll("< */ *font *>","[/font]");
		//****************************************************************
		html = html.replaceAll("\n( *)?","");
		html = html.replaceAll("< *br */? *>","\n");
		//****************************************************************
		html = html.replaceAll("<!--.*?-->","");
		html = html.replaceAll("<!-- *","");
		html = html.replaceAll(" *-->","");
		//html = html.replaceAll("< *script.*?>.*?< */script *>","");
		//html = html.replaceAll("< *tbody( .*?)?>","");
		//html = html.replaceAll("< */ *tbody *>","");
		//html = html.replaceAll("< *fieldset( .*?)?>","");
		//html = html.replaceAll("< */ *fieldset *>","");
		//html = html.replaceAll("< *span( .*?)?>","");
		//html = html.replaceAll("< */ *span *>","");
		//html = html.replaceAll("< *p( .*?)?>","");
		//html = html.replaceAll("< */ *p *>","");
		html = html.replaceAll("< *div( .*?)?>","");
		html = html.replaceAll("< */ *div *>","\n");
		//html = html.replaceAll("< *pre( .*?)?>","");
		//html = html.replaceAll("< */ *pre *>","");
		//html = html.replaceAll("< *nobr( .*?)?>","");
		//html = html.replaceAll("< */ *nobr *>","");
		//html = html.replaceAll("< *fieldset( .*?)?>","");
		//html = html.replaceAll("< */ *fieldset *>","");
		//html = html.replaceAll("< *noindex( .*?)?>","");
		//html = html.replaceAll("< */ *noindex *>","");
		//HTML5
		//html = html.replaceAll("< *article( .*?)?>","");
		//html = html.replaceAll("< */ *article *>","");
		//html = html.replaceAll("< *aside( .*?)?>","");
		//html = html.replaceAll("< */ *aside *>","");
		html = html.replaceAll("< *cite( .*?)?>","[i]");
		html = html.replaceAll("< */ *cite *>","[/i]");
		html = html.replaceAll("< *dfn( .*?)?>","[i]");
		html = html.replaceAll("< */ *dfn *>","[/i]");
		html = html.replaceAll("< *var( .*?)?>","[i]");
		html = html.replaceAll("< */ *var *>","[/i]");
		//****************************************************************
		html = html.replaceAll("((<code>(.*?)</code>)|(<.*?>))","$2");
		html = html.replaceAll("< *code( .*?)?>","[code]");
		html = html.replaceAll("< */ *code *>","[/code]");
			
		//LOG.info("//Parsing END");
		return html;
	}
	public static String parse_bboff(String html)
	{
		//LOG.info("//Parsing START");
		try 
		{
			Document doc = Jsoup.parse(html);
			doc.select("label").remove();
			doc.select("input").remove();
			doc.select("script").remove();
			doc.select("textarea").remove();

			doc.select("*").removeAttr("alt");
			doc.select("*").removeAttr("title");
			doc.select("*").removeAttr("style");
			doc.select("*").removeAttr("id");
			doc.select("*").removeAttr("class");
			doc.select("*").removeAttr("width");
			doc.select("*").removeAttr("height");
			doc.select("*").removeAttr("target");
		
			html = doc.body().html();
			
		}catch(Exception e){System.err.println(e);}
		
		//for(Element elm :doc.getAllElements()){if(elm.tagName()=="embed"){String src = elm.attr("src");}}
		html = html.replaceAll("&nbsp;|&#160;"," ");
		html = html.replaceAll("&iexcl;|&#161;","¡");
		html = html.replaceAll("&cent;|&#162;","¢");
		html = html.replaceAll("&pound;|&#163;","£");
		html = html.replaceAll("&curren;|&#164;","¤");
		html = html.replaceAll("&yen;|&#165;","¥");
		html = html.replaceAll("&brvbar;|&#166;","¦");
		html = html.replaceAll("&sect;|&#167;","§");
		html = html.replaceAll("&uml;|&#168;","¨");
		html = html.replaceAll("&copy;|&#169;","©");
		html = html.replaceAll("&ordf;|&#170;","ª");
		html = html.replaceAll("&laquo;|&#171;","«");
		html = html.replaceAll("&raquo;|&#187;","»");
		html = html.replaceAll("&not;|&#172;","¬");
		html = html.replaceAll("&reg;|&#174;","®");
		html = html.replaceAll("&macr;|&#175;","¯");
		html = html.replaceAll("&deg;|&#176;","°");
		html = html.replaceAll("&plusmn;|&#177;","±");
		html = html.replaceAll("&sup2;|&#178;","²");
		html = html.replaceAll("&sup3;|&#179;","³");
		html = html.replaceAll("&acute;|&#180;","´");
		html = html.replaceAll("&micro;|&#181;","µ");
		html = html.replaceAll("&para;|&#182;","¶");
		html = html.replaceAll("&middot;|&#183;","·");
		html = html.replaceAll("&cedil;|&#184;","¸");
		html = html.replaceAll("&sup1;|&#185;","¹	");
		html = html.replaceAll("&ordm;|&#186;","º");
		html = html.replaceAll("&frac14;|&#188;","¼");
		html = html.replaceAll("&frac12;|&#189;","½");
		html = html.replaceAll("&#8531;","⅓");
		html = html.replaceAll("&frac34;|&#190;","¾");
		html = html.replaceAll("&iquest;|&#191;","¿");
		html = html.replaceAll("&Agrave;|&#192;","À");
		html = html.replaceAll("&Aacute;|&#193;","Á");
		html = html.replaceAll("&Acirc;|&#194;","Â");
		html = html.replaceAll("&Atilde;|&#195;","Ã");
		html = html.replaceAll("&Auml;|&#196;","Ä");
		html = html.replaceAll("&Aring;|&#197;","Å");
		html = html.replaceAll("&AElig;|&#198;","Æ");
		html = html.replaceAll("&Ccedil;|&#199;","Ç");
		html = html.replaceAll("&Egrave;|&#200;","È");
		html = html.replaceAll("&Eacute;|&#201;","É");
		html = html.replaceAll("&Ecirc;|&#202;","Ê");
		html = html.replaceAll("&Euml;|&#203;","Ë");
		html = html.replaceAll("&Igrave;|&#204;","Ì");
		html = html.replaceAll("&Iacute;|&#205;","Í");
		html = html.replaceAll("&Icirc;|&#206;","Î");
		html = html.replaceAll("&Iuml;|&#207;","Ï");
		html = html.replaceAll("&ETH;|&#208;","Ð");
		html = html.replaceAll("&Ntilde;|&#209;","Ñ");
		html = html.replaceAll("&Ograve;|&#210;","Ò");
		html = html.replaceAll("&Oacute;|&#211;","Ó");
		html = html.replaceAll("&Ocirc;|&#212;","Ô");
		html = html.replaceAll("&Otilde;|&#213;","Õ");
		html = html.replaceAll("&Ouml;|&#214;","Ö");
		html = html.replaceAll("&times;|&#215;","×");
		html = html.replaceAll("&Oslash;|&#216;","Ø");
		html = html.replaceAll("&Ugrave;|&#217;","Ù");
		html = html.replaceAll("&Uacute;|&#218;","Ú");
		html = html.replaceAll("&Ucirc;|&#219;","Û");
		html = html.replaceAll("&Uuml;|&#220;","Ü");
		html = html.replaceAll("&Yacute;|&#221;","Ý");
		html = html.replaceAll("&THORN;|&#222;","Þ");
		html = html.replaceAll("&szlig;|&#223;","ß");
		html = html.replaceAll("&agrave;|&#224;","à");
		html = html.replaceAll("&aacute;|&#225;","á");
		html = html.replaceAll("&acirc;|&#226;","â");
		html = html.replaceAll("&atilde;|&#227;","ã");
		html = html.replaceAll("&auml;|&#228;","ä");
		html = html.replaceAll("&aring;|&#229;","å");
		html = html.replaceAll("&aelig;|&#230;","æ");
		html = html.replaceAll("&ccedil;|&#231;","ç");
		html = html.replaceAll("&egrave;|&#232;","è");
		html = html.replaceAll("&eacute;|&#233;","é");
		html = html.replaceAll("&ecirc;|&#234;","ê");
		html = html.replaceAll("&euml;|&#235;","ë");
		html = html.replaceAll("&igrave;|&#236;","ì");
		html = html.replaceAll("&iacute;|&#237;","í");
		html = html.replaceAll("&icirc;|&#238;","î");
		html = html.replaceAll("&iuml;|&#239;","ï");
		html = html.replaceAll("&eth;|&#240;","ð");
		html = html.replaceAll("&ntilde;|&#241;","ñ");
		html = html.replaceAll("&ograve;|&#242;","ò");
		html = html.replaceAll("&oacute;|&#243;","ó");
		html = html.replaceAll("&ocirc;|&#244;","ô");
		html = html.replaceAll("&otilde;|&#245;","õ");
		html = html.replaceAll("&ouml;|&#246;","ö");
		html = html.replaceAll("&divide;|&#247;","÷");
		html = html.replaceAll("&oslash;|&#248;","ø");
		html = html.replaceAll("&ugrave;|&#249;","ù");
		html = html.replaceAll("&uacute;|&#250;","ú");
		html = html.replaceAll("&ucirc;|&#251;","û");
		html = html.replaceAll("&uuml;|&#252;","ü");
		html = html.replaceAll("&yacute;|&#253;","ý");
		html = html.replaceAll("&thorn;|&#254;","þ");
		html = html.replaceAll("&yuml;|&#255;","ÿ");
		html = html.replaceAll("&fnof;|&#402;","ƒ");
		html = html.replaceAll("&Alpha;|&#913;","Α");
		html = html.replaceAll("&Beta;|&#914;","Β");
		html = html.replaceAll("&Gamma;|&#915;","Γ");
		html = html.replaceAll("&Delta;|&#916;","Δ");
		html = html.replaceAll("&Epsilon;|&#917;","Ε");
		html = html.replaceAll("&Zeta;|&#918;","Ζ");
		html = html.replaceAll("&Eta;|&#919;","Η");
		html = html.replaceAll("&Theta;|&#920;","Θ");
		html = html.replaceAll("&Iota;|&#921;","Ι");
		html = html.replaceAll("&Kappa;|&#922;","Κ");
		html = html.replaceAll("&Lambda;|&#923;","Λ");
		html = html.replaceAll("&Mu;|&#924;","Μ");
		html = html.replaceAll("&Nu;|&#925;","Ν");
		html = html.replaceAll("&Xi;|&#926;","Ξ");
		html = html.replaceAll("&Omicron;|&#927;","Ο");
		html = html.replaceAll("&Pi;|&#928;","Π");
		html = html.replaceAll("&Rho;|&#929;","Ρ");
		html = html.replaceAll("&Sigma;|&#931;","Σ");
		html = html.replaceAll("&Tau;|&#932;","Τ");
		html = html.replaceAll("&Upsilon;|&#933;","Υ");
		html = html.replaceAll("&Phi;|&#934;","Φ");
		html = html.replaceAll("&Chi;|&#935;","Χ");
		html = html.replaceAll("&Psi;|&#936;","Ψ");
		html = html.replaceAll("&Omega;|&#937;","Ω");
		html = html.replaceAll("&alpha;|&#945;","α");
		html = html.replaceAll("&beta;|&#946;","β");
		html = html.replaceAll("&gamma;|&#947;","γ");
		html = html.replaceAll("&delta;|&#948;","δ");
		html = html.replaceAll("&epsilon;|&#949;","ε");
		html = html.replaceAll("&zeta;|&#950;","ζ");
		html = html.replaceAll("&eta;|&#951;","η");
		html = html.replaceAll("&theta;|&#952;","θ");
		html = html.replaceAll("&iota;|&#953;","ι");
		html = html.replaceAll("&kappa;|&#954;","κ");
		html = html.replaceAll("&lambda;|&#955;","λ");
		html = html.replaceAll("&mu;|&#956;","μ");
		html = html.replaceAll("&nu;|&#957;","ν");
		html = html.replaceAll("&xi;|&#958;","ξ");
		html = html.replaceAll("&omicron;|&#959;","ο");
		html = html.replaceAll("&pi;|&#960;","π");
		html = html.replaceAll("&rho;|&#961;","ρ");
		html = html.replaceAll("&sigmaf;|&#962;","ς");
		html = html.replaceAll("&sigma;|&#963;","σ");
		html = html.replaceAll("&tau;|&#964;","τ");
		html = html.replaceAll("&upsilon;|&#965;","υ");
		html = html.replaceAll("&phi;|&#966;","φ");
		html = html.replaceAll("&chi;|&#967;","χ");
		html = html.replaceAll("&psi;|&#968;","ψ");
		html = html.replaceAll("&omega;|&#969;","ω");
		html = html.replaceAll("&thetasy;|&#977;","ϑ");
		html = html.replaceAll("&upsih;|&#978;","ϒ");
		html = html.replaceAll("&piv;|&#982;","ϖ");
		html = html.replaceAll("&bull;|&#8226;","•");
		html = html.replaceAll("&hellip;|&#8230;","…");
		html = html.replaceAll("&prime;|&#8242;","′");
		html = html.replaceAll("&Prime;|&#8243;","″");
		html = html.replaceAll("&oline;|&#8254;","‾");
		html = html.replaceAll("&frasl;|&#8260;","⁄");
		html = html.replaceAll("&weierp;|&#8472;","℘");
		html = html.replaceAll("&image;|&#8465;","ℑ");
		html = html.replaceAll("&real;|&#8476;","ℜ");
		html = html.replaceAll("&trade;|&#8482;","™");
		html = html.replaceAll("&alefsym;|&#8501;","ℵ");
		html = html.replaceAll("&larr;|&#8592;","←");
		html = html.replaceAll("&uarr;|&#8593;","↑");
		html = html.replaceAll("&rarr;|&#8594;","→");
		html = html.replaceAll("&darr;|&#8595;","↓");
		html = html.replaceAll("&#9668;","◄");
		html = html.replaceAll("&#9650;","▲");
		html = html.replaceAll("&#9658;","►");
		html = html.replaceAll("&#9660;","▼");
		html = html.replaceAll("&harr;|&#8596;","↔");
		html = html.replaceAll("&crarr;|&#8629;","↵");
		html = html.replaceAll("&lArr;|&#8656;","⇐");
		html = html.replaceAll("&uArr;|&#8657;","⇑");
		html = html.replaceAll("&rArr;|&#8658;","⇒");
		html = html.replaceAll("&dArr;|&#8659;","⇓");
		html = html.replaceAll("&hArr;|&#8660;","⇔");
		html = html.replaceAll("&forall;|&#8704;","∀");
		html = html.replaceAll("&part;|&#8706;","∂");
		html = html.replaceAll("&exist;|&#8707;","∃");
		html = html.replaceAll("&empty;|&#8709;","∅");
		html = html.replaceAll("&nabla;|&#8711;","∇");
		html = html.replaceAll("&isin;|&#8712;","∈");
		html = html.replaceAll("&notin;|&#8713;","∉");
		html = html.replaceAll("&ni;|&#8715;","∋");
		html = html.replaceAll("&prod;|&#8719;","∏");
		html = html.replaceAll("&sum;|&#8721;","∑");
		html = html.replaceAll("&minus;|&#8722;","−");
		html = html.replaceAll("&lowast;|&#8727;","∗");
		html = html.replaceAll("&radic;|&#8730;","√");
		html = html.replaceAll("&prop;|&#8733;","∝");
		html = html.replaceAll("&infin;|&#8734;","∞");
		html = html.replaceAll("&ang;|&#8736;","∠");
		html = html.replaceAll("&and;|&#8743;","∧");
		html = html.replaceAll("&or;|&#8744;","∨");
		html = html.replaceAll("&cap;|&#8745;","∩");
		html = html.replaceAll("&cup;|&#8746;","∪");
		html = html.replaceAll("&int;|&#8747;","∫");
		html = html.replaceAll("&there4;|&#8756;","∴");
		html = html.replaceAll("&sim;|&#8764;","∼");
		html = html.replaceAll("&cong;|&#8773;","≅");
		html = html.replaceAll("&asymp;|&#8776;","≈");
		html = html.replaceAll("&ne;|&#8800;","≠");
		html = html.replaceAll("&equiv;|&#8801;","≡");
		html = html.replaceAll("&le;|&#8804;","≤");
		html = html.replaceAll("&ge;|&#8805;","≥");
		html = html.replaceAll("&sub;|&#8834;","⊂");
		html = html.replaceAll("&sup;|&#8835;","⊃");
		html = html.replaceAll("&nsub;|&#8836;","⊄");
		html = html.replaceAll("&sube;|&#8838;","⊆");
		html = html.replaceAll("&supe;|&#8839;","⊇");
		html = html.replaceAll("&oplus;|&#8853;","⊕");
		html = html.replaceAll("&otimes;|&#8855;","⊗");
		html = html.replaceAll("&perp;|&#8869;","⊥");
		html = html.replaceAll("&sdot;|&#8901;","⋅");
		html = html.replaceAll("&loz;|&#9674;","◊");
		html = html.replaceAll("&spades;|&#9824;","♠");
		html = html.replaceAll("&clubs;|&#9827;","♣");
		html = html.replaceAll("&hearts;|&#9829;","♥");
		html = html.replaceAll("&diams;|&#9830;","♦");
		html = html.replaceAll("&apos;|&#39;","'");
		html = html.replaceAll("&quot;|&#34;","\"");
		html = html.replaceAll("&amp;|&#38;","&");
		html = html.replaceAll("&lt;|&#60;","<");
		html = html.replaceAll("&gt;|&#62;",">");
		html = html.replaceAll("&OElig;|&#338;","Œ");
		html = html.replaceAll("&oelig;|&#339;","œ");
		html = html.replaceAll("&Scaron;|&#352;","Š");
		html = html.replaceAll("&scaron;|&#353;","š");
		html = html.replaceAll("&Yuml;|&#376;","Ÿ");
		html = html.replaceAll("&circ;|&#710;","ˆ");
		html = html.replaceAll("&tilde;|&#732;","˜");
		html = html.replaceAll("&#8209;","‑");
		html = html.replaceAll("&ndash;|&#8211;","–");
		html = html.replaceAll("&mdash;|&#8212;","—");
		html = html.replaceAll("&lsquo;|&#8216;","‘");
		html = html.replaceAll("&rsquo;|&#8217;","’");
		html = html.replaceAll("&sbquo;|&#8218;","‚");
		html = html.replaceAll("&ldquo;|&#8220;","“");
		html = html.replaceAll("&rdquo;|&#8221;","”");
		html = html.replaceAll("&bdquo;|&#8222;","„");
		html = html.replaceAll("&dagger;|&#8224;","†");
		html = html.replaceAll("&Dagger;|&#8225;","‡");
		html = html.replaceAll("&permil;|&#8240;","‰");
		html = html.replaceAll("&lsaquo;|&#8249;","‹");
		html = html.replaceAll("&rsaquo;|&#8250;","›");
		html = html.replaceAll("&euro;|&#8364;","€");
		html = html.replaceAll("&#8470;","№");
		html = html.replaceAll("&#769;","́");

		html = html.replaceAll("&(.*?);","");//Удаляем все остальные мнемоники
			
		html = html.replaceAll("< *img( .*?)?src *= *('|\")(.*?)('|\")(.*?)? */? *>","$3");
		html = html.replaceAll("< *a( .*?)?href *= *('|\")(.*?)('|\")(.*?)? */? *>","$3 ");
		html = html.replaceAll("< *iframe( .*?)?src *= *('|\")(.*?)('|\")(.*?)? */? *>","$3");
		html = html.replaceAll("< *embed( .*?)?src *= *('|\")(.*?)('|\")(.*?)? */? *>","$3");
		html = html.replaceAll("\n( *)?","");
		html = html.replaceAll("< *br */? *>","\n");
		html = html.replaceAll("<!--.*?-->","");
		html = html.replaceAll("<!-- *","");
		html = html.replaceAll(" *-->","");
		html = html.replaceAll("((<code>(.*?)</code>)|(<.*?>))","$2");
		html = html.replaceAll("< *code( .*?)?>","[ ");
		html = html.replaceAll("< */ *code *>"," ]");
		
		html = html.replaceAll("\\<.*?>","");
		return html;
	}
	
	
}
/*******************************************************************************************************************/
